PACKAGE = generator

SOURCE = \
	CodeEntry.java \
	CodeTable.java \
	Generator.java \
	IntermediateGenerator.java \
	Label.java \
	SymbolTableEntry.java \
	Tuple.java \
	TypeConstants.java \
	TypeHashMap.java

include $(CSUB_ROOT)/Makefile

