PACKAGE = lexer

SOURCE = \
	Lexer.java \
	Token.java \
	TypeToken.java \
	VoidToken.java \
	NumberToken.java \
	IntegerToken.java \
	FloatToken.java \
	KeywordToken.java \
	RelationalOperatorToken.java \
	AssignmentOperatorToken.java \
	PlusOrMinusToken.java \
	CommentToken.java \
	IdentifierToken.java \
	PunctuationToken.java \
	DivOrModToken.java \
	PostfixOperatorToken.java \
	InvalidTokenException.java \
	InvalidToken.java \
	CommentToken.java

# Include main makefile in project root
include $(CSUB_ROOT)/Makefile
