PACKAGE = parser

SOURCE = \
	ParseTableContents.java \
	ParseTable.java \
	Symbol.java \
	Nonterminal.java \
	Terminal.java \
	Production.java \
	TerminalDoesNotMatchException.java \
	Parser.java

include $(CSUB_ROOT)/Makefile
